from quantum.gates.basis_permutation_gate import BasisPermutationGate
from quantum.gates.auto_oracle_gate import AutoOracleGate
from quantum.gates.fourier_addition_gate import FourierAdditionGate
from quantum.gates.modular_fourier_addition_gate import ModularFourierAdditionGate
from quantum.gates.modular_exponentiation_gate import ModularExponentiationGate
