from quantum.gates.basis_permutation_gate import BasisPermutationGate
from quantum.gates.auto_oracle_gate import AutoOracleGate
from quantum.gates.modular_exponentiation_gate import ModularExponentiationGate
